package com.martmists.pipewire.editor.conf

import com.martmists.pipewire.editor.graph.GraphState
import com.martmists.pipewire.editor.graph.Node

class PipeWireExporter {
    fun export(state: GraphState): String {
        val nodes = state.nodes
        val connections = state.connections
        val chainName = state.chainName

        val filterNodes = nodes.values.filter { it.type !in setOf("Source", "Sink") }
        val sourceNode = nodes.values.firstOrNull { it.type == "Source" }
        val sinkNode = nodes.values.firstOrNull { it.type == "Sink" }

        val nodeLines = filterNodes.joinToString("\n") { node ->
            val definition = node.definition
            val skipParameters = setOf("plugin", "label", "node.name", "media.class", "target.object", "audio.format", "audio.channels", "audio.rate", "audio.position")
            val stringBuilder = StringBuilder()
            stringBuilder.appendLine("            {")
            stringBuilder.appendLine("                type = ${definition?.pipewireType ?: "builtin"}")
            stringBuilder.appendLine("                name = ${node.name}")
            if (definition?.pipewireType == "ladspa") {
                stringBuilder.appendLine("                plugin = ${node.params["plugin"] ?: ""}")
                stringBuilder.appendLine("                label = ${node.params["label"] ?: ""}")
            } else {
                definition?.pipewireLabel?.takeIf { it.isNotEmpty() }?.let {
                    stringBuilder.appendLine("                label = $it")
                }
            }
            val controlParams = node.params.filter { it.key !in skipParameters }
                .entries.joinToString(" ") { (key, value) -> "\"$key\" = $value" }
            if (controlParams.isNotEmpty()) {
                stringBuilder.appendLine("                control = { $controlParams }")
            }
            stringBuilder.append("            }")
            stringBuilder.toString()
        }

        val linkLines = connections
            .filter { connection ->
                val fromNode = nodes[connection.fromNode]
                val toNode = nodes[connection.toNode]
                fromNode != null && toNode != null &&
                        fromNode.type !in setOf("Source", "Sink") &&
                        toNode.type !in setOf("Source", "Sink")
            }
            .joinToString("\n") { connection ->
                val fromNode = nodes[connection.fromNode]!!
                val toNode = nodes[connection.toNode]!!
                """            { output = "${fromNode.name}:${connection.fromPort}" input = "${toNode.name}:${connection.toPort}" }"""
            }

        val graphInputs = connections
            .filter { connection -> nodes[connection.fromNode]?.type == "Source" }
            .joinToString(" ") { connection -> "\"${nodes[connection.toNode]?.name}:${connection.toPort}\"" }

        val graphOutputs = connections
            .filter { connection -> nodes[connection.toNode]?.type == "Sink" }
            .joinToString(" ") { connection -> "\"${nodes[connection.fromNode]?.name}:${connection.fromPort}\"" }

        fun formatProperties(node: Node?, defaultName: String, defaultClass: String): String {
            val parameters = node?.params?.filter { it.key != "__items__" } ?: mapOf("node.name" to defaultName, "media.class" to defaultClass)
            val allProps = parameters + mapOf(
                "audio.format" to "S32LE",
                "audio.channels" to "2",
                "audio.rate" to "48000",
                "audio.position" to "[ FL FR ]"
            )
            return allProps.entries.joinToString("\n") { (key, value) ->
                val shouldQuote = value.contains(' ') || value.contains('/') || value.isEmpty()
                val isList = value.trim().startsWith('[')
                val quotedValue = if (shouldQuote && !isList) "\"$value\"" else value
                "            $key = $quotedValue"
            }
        }

        val captureProperties = formatProperties(sourceNode, "filter.capture", "Audio/Sink")
        val playbackProperties = formatProperties(sinkNode, "filter.playback", "Audio/Source")

        return buildString {
            appendLine("# Generated by PipeWire Filter Chain Editor")
            appendLine("# Chain: $chainName")
            appendLine()
            appendLine("context.modules = [")
            appendLine("{   name = libpipewire-module-filter-chain")
            appendLine("    args = {")
            appendLine("        node.description = \"$chainName\"")
            appendLine("        media.name = \"$chainName\"")
            appendLine("        filter.graph = {")
            appendLine("            nodes = [")
            if (nodeLines.isNotEmpty()) appendLine(nodeLines)
            appendLine("            ]")
            appendLine("            links = [")
            if (linkLines.isNotEmpty()) appendLine(linkLines)
            appendLine("            ]")
            appendLine("            inputs = [ $graphInputs ]")
            appendLine("            outputs = [ $graphOutputs ]")
            appendLine("        }")
            appendLine("        capture.props = {")
            appendLine(captureProperties)
            appendLine("        }")
            appendLine("        playback.props = {")
            appendLine(playbackProperties)
            appendLine("        }")
            appendLine("    }")
            appendLine("}")
            appendLine("]")
        }
    }
}
